name: CI/CD Pipeline for Backend

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push Docker image to ECR
      run: |
        cd backend
        docker build -t cicd-backend .
        docker tag cicd-backend:latest 808872802370.dkr.ecr.us-east-1.amazonaws.com/cicd-backend:latest
        docker push 808872802370.dkr.ecr.us-east-1.amazonaws.com/cicd-backend:latest

    - name: Deploy to EC2
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > ec2-key.pem
        chmod 400 ec2-key.pem
        ssh -o StrictHostKeyChecking=no -i ec2-key.pem ubuntu@54.204.165.103 << 'EOF'
          sudo docker rm -f backend || true
          sudo docker pull 808872802370.dkr.ecr.us-east-1.amazonaws.com/cicd-backend:latest
          sudo docker run -d --name backend -p 3000:3000 808872802370.dkr.ecr.us-east-1.amazonaws.com/cicd-backend:latest
        EOF
