name: Backend CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 808872802370.dkr.ecr.us-east-1.amazonaws.com

    - name: Build, Tag, and Push Docker Image to ECR
      run: |
        docker build -t cicd-backend ./backend
        docker tag cicd-backend:latest 808872802370.dkr.ecr.us-east-1.amazonaws.com/cicd-backend:latest
        docker push 808872802370.dkr.ecr.us-east-1.amazonaws.com/cicd-backend:latest

    - name: Deploy to EC2
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > ec2-key.pem
        chmod 400 ec2-key.pem
        ssh -o StrictHostKeyChecking=no -i ec2-key.pem ubuntu@54.204.165.103 << 'EOF'
          docker rm -f backend || true
          docker pull 808872802370.dkr.ecr.us-east-1.amazonaws.com/cicd-backend:latest
          docker run -d --name backend -p 3000:3000 808872802370.dkr.ecr.us-east-1.amazonaws.com/cicd-backend:latest
        EOF
