name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 54.204.165.103 >> ~/.ssh/known_hosts

    - name: Login to Amazon ECR
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region us-east-1
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 808872802370.dkr.ecr.us-east-1.amazonaws.com

    - name: SSH and Deploy Docker Container
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@54.204.165.103 << 'EOF'
          docker stop backend || true
          docker rm backend || true
          docker pull 808872802370.dkr.ecr.us-east-1.amazonaws.com/cicd-backend:latest
          docker run -d --name backend -p 3000:3000 808872802370.dkr.ecr.us-east-1.amazonaws.com/cicd-backend:latest
        EOF
