name: Backend CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_TAG: latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, Tag, and Push Docker Image to ECR
      run: |
        cd backend
        docker build -t cicd-backend .
        docker tag cicd-backend:latest ${{ steps.login-ecr.outputs.registry }}/cicd-backend:latest
        docker push ${{ steps.login-ecr.outputs.registry }}/cicd-backend:latest

    - name: Deploy to EC2
      run: |
        echo "$EC2_SSH_KEY" > private_key.pem
        chmod 400 private_key.pem

        ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@54.204.165.103 << 'EOF'
          # Remove container using port 3000
          EXISTING_CONTAINER=$(sudo docker ps -q --filter "publish=3000")
          if [ -n "$EXISTING_CONTAINER" ]; then
            echo "Removing container using port 3000..."
            sudo docker rm -f $EXISTING_CONTAINER
          fi

          # Kill any leftover process on port 3000
          PORT_IN_USE=$(sudo lsof -t -i:3000)
          if [ -n "$PORT_IN_USE" ]; then
            echo "Killing leftover process on port 3000: $PORT_IN_USE"
            sudo kill -9 $PORT_IN_USE
          fi

          # Pull latest image and run container
          aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin ${AWS_ECR_URL}
          sudo docker pull ${AWS_ECR_URL}/cicd-backend:latest
          sudo docker run -d -p 3000:3000 --name backend ${AWS_ECR_URL}/cicd-backend:latest
        EOF
      env:
        AWS_ECR_URL: ${{ steps.login-ecr.outputs.registry }}
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
